sudo: required
language: python
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker build -t enriquesmw/docker-react -f Dockerfile.dev .

script:
  - docker run enriquesmw/docker-react ls -l && echo $?