sudo: required
language: python
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker build -t enriquesmw/docker-react -f Dockerfile.dev .

script:
  - docker run enriquesmw/docker-react ls -l && echo $?

deploy:
  - provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-west-2-648432657698"
    bucket_path: "docker-react"
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY